# Nombre de la aplicación
spring.application.name=Bosquejo-Backend

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/BD_BOSQUEJO
spring.datasource.username=postgres
spring.datasource.password=luigipapu321
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080

spring.security.user.name=admin
spring.security.user.password=admin

# Jackson Configuration
spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT Configuration
jwt.secret=jdsaidjwhfuwfaiw00000iwwqi00i_must_be_32_chars_min
jwt.expiration-ms=3600000

# Spring Mail (Email Configuration)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dylanpoma4@gmail.com
spring.mail.password=wmknschmzekbyrmh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 Client ID
oauth2.google.client-id=828039070580-33kssas6vujhm90ofclcundsc8ko0fsj.apps.googleusercontent.com